### ISSUE TITLE
Change name of GammaPy

### ISSUE THREAD

**Issue by skilkis** [skilkis/numfoil#9]
The GammaPy repository and package name conflicts with [Gammapy](https://gammapy.org/) a Python package for Gamma-ray astronomy. The name JITFoil mirrors the name of XFoil and JavaFoil, while representing that the code is high-performance and compiled JIT with Numba. Other available names include:
- NumFoil (Numba + NumPy XFoil)
- VecFoil (Vectorized XFoil)
- ParFoil (Parallelized XFoil)

**Comment by skilkis** [comment]
@kswannet which name do you like best from the list given above?

**Comment by kswannet** [comment]
Probably either JITFoil or NumFoil

**Comment by skilkis** [comment]
@kswannet cool! I think I'll go with NumFoil then, it seems like it has more significance to more people
